#!/usr/bin/env bash

. "$(dirname "$0")/harness.sh"

printf "Test group: the same sources build the same folders twice\n"

"$SDK/build" "$PLUGIN" "$WORK/again" "$WORK/INSTALL-again.md" >/dev/null
assert "the build runs twice" "$?" "nothing can be shipped from these sources"

diff --recursive --unified "$BUILT" "$WORK/again" > "$WORK/drift"
assert "and writes the same thing both times" "$?" \
  "the build is not deterministic, so a committed folder drifts on every run"

diff --unified "$WORK/INSTALL.md" "$WORK/INSTALL-again.md" > "$WORK/page-drift"
assert "and the same install page" "$?" "the page drifts on every run"

if [ -d "$PLUGIN/distributions" ]; then
  printf "\nTest group: what the plugin ships is what its sources build\n"

  diff --recursive --unified "$PLUGIN/distributions" "$BUILT" > "$WORK/committed-drift"
  assert "every committed distribution matches the build" "$?" \
    "an install would copy something no source says - run the build"
fi

printf "\nTest group: every folder holds what its harness declares, and nothing else\n"

for distribution in $(distributions); do
  declared="$SDK/harnesses/$distribution/harness.json"
  for part in hooks skills commands; do
    case "$part" in
      hooks) held="hooks/lib/settings.sh" ;;
      skills) held="skills/update/SKILL.md" ;;
      commands) held="commands/update.md" ;;
    esac

    if jq --exit-status --arg part "$part" '.ships | index($part)' "$declared" >/dev/null; then
      [ -e "$BUILT/$distribution/$held" ]
      assert "$distribution ships $part" "$?" \
        "it declares $part and an install from that folder is missing it"
    else
      [ ! -e "$BUILT/$distribution/$part" ]
      assert "$distribution ships no $part" "$?" \
        "it declares none and the folder holds $part anyway, so an install copies what nothing there reads"
    fi
  done

  grep --quiet --fixed-strings '## Installing' "$BUILT/$distribution/README.md"
  assert "$distribution says how it is installed" "$?" \
    "the folder is there and nothing tells a reader what to do with it"
done

printf "\nTest group: a generated file says so\n"

for generated in "$BUILT"/*/README.md "$BUILT"/*/clients/*.md "$BUILT"/*/hooks/lib/settings.sh \
  "$BUILT"/*/skills/reload/SKILL.md "$BUILT"/*/skills/update/SKILL.md \
  "$BUILT"/*/skills/uninstall/SKILL.md "$BUILT"/*/skills/settings/SKILL.md; do
  [ -f "$generated" ] || continue
  grep --quiet --fixed-strings 'Generated by' "$generated"
  assert "${generated#$BUILT/} says it is generated" "$?" \
    "a reader edits it, runs the build, and loses the edit"
done

printf "\nTest group: a skill the plugin wrote is carried, not rewritten\n"

for folder in "$PLUGIN"/skills/*/; do
  [ -f "$folder/SKILL.md" ] || continue
  named="$(basename "$folder")"
  for distribution in $(distributions); do
    [ -f "$BUILT/$distribution/skills/$named/SKILL.md" ] || continue
    cmp --silent "$folder/SKILL.md" "$BUILT/$distribution/skills/$named/SKILL.md"
    assert "$distribution carries $named as the plugin wrote it" "$?" \
      "the build changed it, so the plugin's source is not what an install copies"
  done
done

printf "\nTest group: nothing the build writes still holds a placeholder\n"

left="$(grep --recursive --only-matching '{{[a-z-]*}}' "$BUILT" "$WORK/INSTALL.md" | sort --unique || true)"
[ -z "$left" ]
assert "every {{name}} was filled in" "$?" "$left reached a reader unfilled"

counted
