#!/usr/bin/env bash

. "$(dirname "$0")/harness.sh"

PAGE="$PLUGIN/COMPATIBILITY.md"

printf "Test group: every client says what it runs\n"

for source in "$SDK"/clients/*/client.json; do
  named="$(basename "$(dirname "$source")")"
  for part in hooks skills settings; do
    [ -n "$(jq --raw-output "if .runs.$part == null then empty else .runs.$part end" "$source")" ]
    assert "$named says whether it runs $part" "$?" \
      "the table cannot say Supported or Partial without it"
  done
done

printf "\nTest group: every row of the map names a client the SDK has, or none\n"

while read -r client; do
  [ -f "$SDK/clients/$client/client.json" ]
  assert "compatibility.json names $client, which exists" "$?" \
    "a row links a folder that is not there"
done < <(jq --raw-output '.vendors[].products[].client // empty' "$SDK/compatibility.json" | sort --unique)

printf "\nTest group: the page is written, and written from that map\n"

[ -f "$PAGE" ]
assert "the build wrote COMPATIBILITY.md" "$?" "the plugin has no page saying where it installs"

grep --quiet --fixed-strings 'Generated by' "$PAGE"
assert "and says it is generated" "$?" "a reader edits it and loses the edit"

while read -r vendor; do
  grep --quiet --fixed-strings "## $vendor" "$PAGE"
  assert "$vendor has a section" "$?" "the map names it and the page does not"
done < <(jq --raw-output '.vendors[].vendor' "$SDK/compatibility.json")

rows="$(grep --count '^| ' "$PAGE")"
declared="$(jq '[.vendors[].products[]] | length' "$SDK/compatibility.json")"
[ "$rows" -ge "$declared" ]
assert "every product row reached the page" "$?" \
  "the map has $declared rows and the page has $rows including its headers"

printf "\nTest group: Partial is said where something does not reach a session\n"

# Pi runs no skills, so a plugin's skills do not arrive there.
grep --quiet --extended-regexp '^\| Pi \|.*\| Partial \|' "$PAGE"
assert "Pi reads Partial, because it carries no skills" "$?" \
  "$(grep '^| Pi |' "$PAGE")"

grep --quiet --extended-regexp '^\| Claude Code \| CLI \| Local \|.*\| Supported \|' "$PAGE"
assert "Claude Code on your machine reads Supported" "$?" \
  "$(grep '^| Claude Code | CLI' "$PAGE")"

printf "\nTest group: a Partial row owes the reader the reason\n"

while read -r client; do
  note="$(jq --raw-output '.note // empty' "$SDK/clients/$client/client.json")"
  [ -n "$note" ] || continue
  grep --quiet --fixed-strings "$note" "$PAGE"
  assert "the page carries $client's note" "$?" "it says Partial and never says why"
done < <(jq --raw-output '.clients[]?' "$PLUGIN/plugin.json" 2>/dev/null)

printf "\nTest group: a plugin gets every client it can reach, without naming any\n"

named="$(jq --raw-output '.clients // empty | length' "$MANIFEST")"
if [ -z "$named" ]; then
  for client in $(jq --raw-output '.serves[]' "$SDK"/harnesses/*/harness.json); do
    # A client it cannot reach is one running neither hooks nor skills.
    runs_hooks="$(jq --raw-output 'if .runs.hooks == null then empty else .runs.hooks end' "$SDK/clients/$client/client.json")"
    runs_skills="$(jq --raw-output 'if .runs.skills == null then empty else .runs.skills end' "$SDK/clients/$client/client.json")"
    [ "$runs_hooks" = "true" ] || [ "$runs_skills" = "true" ] || continue

    found=""
    for distribution in $(distributions); do
      [ -f "$BUILT/$distribution/clients/$client.md" ] && found=1
    done
    [ -n "$found" ]
    assert "$client got a page without the manifest naming it" "$?" \
      "the plugin can reach it and the build left it out"
  done
fi

printf "\nTest group: what a client runs is the SDK's, not a plugin's to claim\n"

# A plugin override holding only a name used to make every client look
# unreachable, and the build wrote nothing at all while exiting 0.
override="$WORK/override"
cp -R "$PLUGIN" "$override"
mkdir -p "$override/clients/codex"
printf '{\n\t"name": "Codex"\n}\n' > "$override/clients/codex/client.json"

"$SDK/build" "$override" "$WORK/override-out" "$WORK/override.md" >/dev/null 2>&1
assert "a plugin naming a client without saying what it runs still builds" "$?" \
  "the build read runs from the plugin and found none"

[ -d "$WORK/override-out/codex" ]
assert "and that client still gets its folder" "$?" "the override made it unreachable"

printf "\nTest group: a build that writes nothing says so\n"

empty="$WORK/empty-plugin"
mkdir -p "$empty"
printf '{"name":"none","version":"0.0.1","clients":[],"hooks":{}}\n' > "$empty/plugin.json"
said="$("$SDK/build" "$empty" "$WORK/empty-out" "$WORK/empty.md" 2>&1)"
outcome="$?"
[ "$outcome" != "0" ]
assert "it fails rather than exiting 0 with no folders" "$?" "it exited 0 having built nothing"

printf '%s' "$said" | grep --quiet --fixed-strings 'nothing was built'
assert "and says what happened" "$?" "it said '$said'"

counted
