#!/usr/bin/env bash

# build sets sdk, plugin, out and page before sourcing this, and everything
# this sets is read by the other files in builder/. shellcheck reads one file
# at a time and can see neither side of that.
# shellcheck disable=SC2154,SC2034

# The plugin's manifest, read once, and everything written with its name left
# open. Every other file in builder/ reads what this sets.

manifest="$plugin/plugin.json"
[ -f "$manifest" ] || { printf 'no plugin.json in %s\n' "$plugin" >&2; exit 1; }

# plugin.json names each hook under a common event name, and a hook can be an
# object with an `on` list saying which tool calls, or which of the event's own
# values, it runs for:
#
#   "before_tool": [ { "script": "guard.sh", "on": ["bash(git *)", "edit(*.sh)"] } ]
#
# Everything after this reads one shape: each event under the name the
# registrations carry, holding script names, with the `on` lists kept aside in
# hook_on. A plugin that still names events that way is read as it is.
source_manifest="$manifest"
unknown_events="$(jq --raw-output --slurpfile events "$sdk/builder/events.json" '
  ($events[0].events | keys + [.[]]) as $known
  | (.hooks // {}) | keys[] | select(. as $key | $known | index($key) | not)
' "$source_manifest")"
if [ -n "$unknown_events" ]; then
  printf 'plugin.json names hooks under an event the SDK does not know: %s\n\n' "$(printf '%s' "$unknown_events" | tr '\n' ' ')" >&2
  printf 'The events it knows are in builder/events.json.\n' >&2
  exit 1
fi
manifest="$(mktemp)"
trap 'rm -f "$manifest"' EXIT
jq --slurpfile events "$sdk/builder/events.json" '
  $events[0].events as $names
  | .hook_on = ([(.hooks // {}) | to_entries[] | .value[]?
      | select(type == "object" and ((.on // []) | length) > 0) | {key: .script, value: .on}] | from_entries)
  | .hooks = ((.hooks // {}) | with_entries(
      .key |= ($names[.] // .)
      | .value |= map(if type == "object" then .script else . end)))
' "$source_manifest" > "$manifest"

says() { jq --raw-output "$1 // empty" "$manifest"; }

name="$(says .name)"
version="$(says .version)"
display="$(says '.displayName // .name')"
repository="$(says .repository)"
[ -n "$name" ] && [ -n "$version" ] || { printf 'plugin.json needs a name and a version\n' >&2; exit 1; }

# What this SDK is, and what the plugin says it needs. A plugin that asks for
# more than this copy has would be built by rules it has not got.
sdk_version="$(jq --raw-output '.version' "$sdk/package.json")"
sdk_wanted="$(says '."ai-plugin-sdk".version')"
if [ -n "$sdk_wanted" ] && [ "$sdk_wanted" != "$sdk_version" ] \
  && [ "$(printf '%s\n%s\n' "$sdk_version" "$sdk_wanted" | sort --version-sort | tail -1)" = "$sdk_wanted" ]; then
  printf '%s asks for ai-plugin-sdk %s, and this copy is %s.\n\n' "$name" "$sdk_wanted" "$sdk_version" >&2
  printf 'Pull the SDK, or lower the version in plugin.json.\n' >&2
  exit 1
fi

prefix="$(printf '%s' "$name" | tr '[:lower:]-' '[:upper:]_')"
# Not a path this shell resolves: it is written into a page for a person to
# read, where ~ is what they want to see.
# shellcheck disable=SC2088
home="~/.$name"
generated="Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead."
published="https://github.com/$repository/blob/main"

# The hooks a distribution registers: the plugin's own, and the SDK's own
# beside them. What the session start hooks print reaches a client that drops
# it only if something prints it again on the first prompt, so a plugin that
# has a session start print gets the pair of hooks that carries it.
effective_hooks() {
  jq --arg repository "$repository" '
    ["mark-session-started.sh", "print-session-start-if-missed.sh", "replay-notes.sh",
     "note-a-new-version.sh"] as $ours
    | if ((.hooks // {}) | length) == 0 then {} else
      .hooks
      # A plugin that names a hook the SDK owns is naming a file it did not
      # write, and the SDK registers that file itself. Naming it twice would
      # run it twice.
      | with_entries(.value |= (. - $ours))
      | (if ((.SessionStart // []) | length) > 0 then
           .SessionStart += ["mark-session-started.sh"]
           | .UserPromptSubmit = (["print-session-start-if-missed.sh"] + (.UserPromptSubmit // []))
         else . end)
      # A note the last turn left is read last, next to the prompt it is about.
      | .UserPromptSubmit = ((.UserPromptSubmit // []) + ["replay-notes.sh"])
      # A plugin with nowhere to read a published version from is never told
      # there is a newer one.
      | (if $repository == "" then .
         else .UserPromptSubmit = (["note-a-new-version.sh"] + .UserPromptSubmit) end)
    end
  ' "$manifest"
}

# Which of the SDK's own hooks this plugin's distributions carry: whatever the
# registration above names, so a file copied and a file registered cannot differ.
sdk_hooks() {
  local script named
  for script in "$sdk"/hooks/*.sh; do
    named="$(basename "$script")"
    effective_hooks | jq --exit-status --arg s "$named" 'any(.[]?[]; . == $s)' >/dev/null \
      && printf '%s\n' "$named"
  done
}

# The hooks a person is asked to trust, counted once for every page that says
# how many there are.
hook_count="$(effective_hooks | jq '[.[]?[]] | length')"

# The script a page tells someone to run by hand to be given what a session is
# given at its start.
session_start="$(jq --raw-output '.hooks.SessionStart[0] // empty' "$manifest")"

# The same map a harness that spawns the scripts itself has to be handed.
hooks_by_event="$(effective_hooks | jq --compact-output .)"

# How the harness being built names the plugin's directory. It differs per
# harness and is read by everything that fills a page, so it is set in one named
# place rather than passed through six functions that only carry it onwards.
harness_root=""
use_harness_root() { harness_root="$1"; }

# Everything written with the plugin's name left open, filled in here.
filled() {
  sed -e "s|{{name}}|$name|g" \
      -e "s|{{display}}|$display|g" \
      -e "s|{{version}}|$version|g" \
      -e "s|{{repository}}|$repository|g" \
      -e "s|{{prefix}}|$prefix|g" \
      -e "s|{{home}}|$home|g" \
      -e "s|{{hooks}}|$hook_count|g" \
      -e "s|{{session-start}}|$session_start|g" \
      -e "s|{{hooks-by-event}}|$hooks_by_event|g" \
      -e "s|{{root}}|${1-$harness_root}|g"
}

# A default names the two directories before there is a home to point at. A
# person reading a page wants the path, so it is filled in here.
pathed() { sed -e "s|{state}|$home/state|g" -e "s|{home}|$home|g"; }

# The settings a plugin declares, over the ones every plugin gets. The built-in
# ones are filled first, because one of them names the plugin's repository.
# A plugin with no repository has nowhere to read a published version from, so
# it gets neither the update check nor the settings that shape it.
settings_json() {
  local builtin="$sdk/lib/settings.json" held
  # An empty root, because a setting is the same on every harness.
  held="$(filled '' < "$builtin")"
  if [ -z "$repository" ]; then
    held="$(printf '%s' "$held" | jq 'del(.UPDATE_CHECK, .UPDATE_CHECK_DAYS, .VERSION_SOURCE)')"
  fi
  printf '%s' "$held" | jq --slurpfile declared <(jq '.settings // {}' "$manifest") \
    '. * ($declared[0] // {})'
}
