#!/usr/bin/env bash

# build sets sdk, plugin, out and page before sourcing this, and everything
# this sets is read by the other files in builder/. shellcheck reads one file
# at a time and can see neither side of that.
# shellcheck disable=SC2154,SC2034

# The plugin's manifest, read once, and everything written with its name left
# open. Every other file in builder/ reads what this sets.

manifest="$plugin/plugin.json"
[ -f "$manifest" ] || { printf 'no plugin.json in %s\n' "$plugin" >&2; exit 1; }

says() { jq --raw-output "$1 // empty" "$manifest"; }

name="$(says .name)"
version="$(says .version)"
display="$(says '.displayName // .name')"
repository="$(says .repository)"
[ -n "$name" ] && [ -n "$version" ] || { printf 'plugin.json needs a name and a version\n' >&2; exit 1; }

prefix="$(printf '%s' "$name" | tr '[:lower:]-' '[:upper:]_')"
# Not a path this shell resolves: it is written into a page for a person to
# read, where ~ is what they want to see.
# shellcheck disable=SC2088
home="~/.$name"
generated="Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead."
published="https://github.com/$repository/blob/main"

# The hooks a distribution registers: the plugin's own, and the SDK's own
# beside them. What the session start hooks print reaches a client that drops
# it only if something prints it again on the first prompt, so a plugin that
# has a session start print gets the pair of hooks that carries it.
effective_hooks() {
  jq '
    ["mark-session-started.sh", "print-session-start-if-missed.sh", "replay-notes.sh"] as $ours
    | if ((.hooks // {}) | length) == 0 then {} else
      .hooks
      # A plugin that names a hook the SDK owns is naming a file it did not
      # write, and the SDK registers that file itself. Naming it twice would
      # run it twice.
      | with_entries(.value |= (. - $ours))
      | (if ((.SessionStart // []) | length) > 0 then
           .SessionStart += ["mark-session-started.sh"]
           | .UserPromptSubmit = (["print-session-start-if-missed.sh"] + (.UserPromptSubmit // []))
         else . end)
      # A note the last turn left is read last, next to the prompt it is about.
      | .UserPromptSubmit = ((.UserPromptSubmit // []) + ["replay-notes.sh"])
    end
  ' "$manifest"
}

# Which of the SDK's own hooks this plugin's distributions carry: whatever the
# registration above names, so a file copied and a file registered cannot differ.
sdk_hooks() {
  local script named
  for script in "$sdk"/hooks/*.sh; do
    named="$(basename "$script")"
    effective_hooks | jq --exit-status --arg s "$named" 'any(.[]?[]; . == $s)' >/dev/null \
      && printf '%s\n' "$named"
  done
}

# The hooks a person is asked to trust, counted once for every page that says
# how many there are.
hook_count="$(effective_hooks | jq '[.[]?[]] | length')"

# The script a page tells someone to run by hand to be given what a session is
# given at its start.
session_start="$(jq --raw-output '.hooks.SessionStart[0] // empty' "$manifest")"

# The same map a harness that spawns the scripts itself has to be handed.
hooks_by_event="$(effective_hooks | jq --compact-output .)"

# How the harness being built names the plugin's directory. It differs per
# harness and is read by everything that fills a page, so it is set in one named
# place rather than passed through six functions that only carry it onwards.
harness_root=""
use_harness_root() { harness_root="$1"; }

# Everything written with the plugin's name left open, filled in here.
filled() {
  sed -e "s|{{name}}|$name|g" \
      -e "s|{{display}}|$display|g" \
      -e "s|{{version}}|$version|g" \
      -e "s|{{repository}}|$repository|g" \
      -e "s|{{prefix}}|$prefix|g" \
      -e "s|{{home}}|$home|g" \
      -e "s|{{hooks}}|$hook_count|g" \
      -e "s|{{session-start}}|$session_start|g" \
      -e "s|{{hooks-by-event}}|$hooks_by_event|g" \
      -e "s|{{root}}|${1-$harness_root}|g"
}

# A default names the two directories before there is a home to point at. A
# person reading a page wants the path, so it is filled in here.
pathed() { sed -e "s|{state}|$home/state|g" -e "s|{home}|$home|g"; }

# The settings a plugin declares, over the ones every plugin gets.
settings_json() {
  jq --slurpfile builtin "$sdk/lib/settings.json" \
    '($builtin[0] // {}) * (.settings // {})' "$manifest"
}
